CREATE TABLE cities
(
    id           bigserial  not null
        constraint cities_pk
            primary key,
    city_id      bigint,
    name         text,
    country_code varchar(3),
    language     varchar(3) not null
);

create index cities_city_index
    on cities (name);

create index cities_asc_index on cities (language asc, name asc);

INSERT INTO cities(city_id, name, country_code, language)
VALUES (1, 'Adana', 'TR', 'TR'),
       (2, 'Adıyaman', 'TR', 'TR'),
       (3, 'Afyonkarahisar', 'TR', 'TR'),
       (4, 'Ağrı', 'TR', 'TR'),
       (5, 'Aksaray', 'TR', 'TR'),
       (6, 'Amasya', 'TR', 'TR'),
       (7, 'Ankara', 'TR', 'TR'),
       (8, 'Antalya', 'TR', 'TR'),
       (9, 'Ardahan', 'TR', 'TR'),
       (10, 'Artvin', 'TR', 'TR'),
       (11, 'Aydın', 'TR', 'TR'),
       (12, 'Balıkesir', 'TR', 'TR'),
       (13, 'Bartın', 'TR', 'TR'),
       (14, 'Batman', 'TR', 'TR'),
       (15, 'Bayburt', 'TR', 'TR'),
       (16, 'Bilecik', 'TR', 'TR'),
       (17, 'Bingöl', 'TR', 'TR'),
       (18, 'Bitlis', 'TR', 'TR'),
       (19, 'Bolu', 'TR', 'TR'),
       (20, 'Burdur', 'TR', 'TR'),
       (21, 'Bursa', 'TR', 'TR'),
       (22, 'Çanakkale', 'TR', 'TR'),
       (23, 'Çankırı', 'TR', 'TR'),
       (24, 'Çorum', 'TR', 'TR'),
       (25, 'Denizli', 'TR', 'TR'),
       (26, 'Diyarbakır', 'TR', 'TR'),
       (27, 'Düzce', 'TR', 'TR'),
       (28, 'Edirne', 'TR', 'TR'),
       (29, 'Elazığ', 'TR', 'TR'),
       (30, 'Erzincan', 'TR', 'TR'),
       (31, 'Erzurum', 'TR', 'TR'),
       (32, 'Eskişehir', 'TR', 'TR'),
       (33, 'Gaziantep', 'TR', 'TR'),
       (34, 'Giresun', 'TR', 'TR'),
       (35, 'Gümüşhane', 'TR', 'TR'),
       (36, 'Hakkari', 'TR', 'TR'),
       (37, 'Hatay', 'TR', 'TR'),
       (38, 'Iğdır', 'TR', 'TR'),
       (39, 'Isparta', 'TR', 'TR'),
       (40, 'Istanbul', 'TR', 'TR'),
       (41, 'Izmir', 'TR', 'TR'),
       (42, 'Kahramanmaraş', 'TR', 'TR'),
       (43, 'Karabük', 'TR', 'TR'),
       (44, 'Karaman', 'TR', 'TR'),
       (45, 'Kars', 'TR', 'TR'),
       (46, 'Kastamonu', 'TR', 'TR'),
       (47, 'Kayseri', 'TR', 'TR'),
       (48, 'Kırıkkale', 'TR', 'TR'),
       (49, 'Kırklareli', 'TR', 'TR'),
       (50, 'Kırşehir', 'TR', 'TR'),
       (51, 'Kilis', 'TR', 'TR'),
       (52, 'Kocaeli', 'TR', 'TR'),
       (53, 'Konya', 'TR', 'TR'),
       (54, 'Kütahya', 'TR', 'TR'),
       (55, 'Malatya', 'TR', 'TR'),
       (56, 'Manisa', 'TR', 'TR'),
       (57, 'Mardin', 'TR', 'TR'),
       (58, 'Mersin', 'TR', 'TR'),
       (59, 'Muğla', 'TR', 'TR'),
       (60, 'Muş', 'TR', 'TR'),
       (61, 'Nevşehir', 'TR', 'TR'),
       (62, 'Niğde', 'TR', 'TR'),
       (63, 'Ordu', 'TR', 'TR'),
       (64, 'Osmaniye', 'TR', 'TR'),
       (65, 'Rize', 'TR', 'TR'),
       (66, 'Sakarya', 'TR', 'TR'),
       (67, 'Samsun', 'TR', 'TR'),
       (68, 'Siirt', 'TR', 'TR'),
       (69, 'Sinop', 'TR', 'TR'),
       (70, 'Sivas', 'TR', 'TR'),
       (71, 'Şanlıurfa', 'TR', 'TR'),
       (72, 'Şırnak', 'TR', 'TR'),
       (73, 'Tekirdağ', 'TR', 'TR'),
       (74, 'Tokat', 'TR', 'TR'),
       (75, 'Trabzon', 'TR', 'TR'),
       (76, 'Tunceli', 'TR', 'TR'),
       (77, 'Uşak', 'TR', 'TR'),
       (78, 'Van', 'TR', 'TR'),
       (79, 'Yalova', 'TR', 'TR'),
       (80, 'Yozgat', 'TR', 'TR'),
       (81, 'Zonguldak', 'TR', 'TR');