CREATE TABLE brands
(
    id           bigserial not null
        constraint brands_pk
            primary key,
    name         text      not null,
    feature_type text      not null
);

create index car_brands_asc_index on brands (name asc);

INSERT INTO brands(name, feature_type)
VALUES ('Acura', 'CAR_BRAND'),
       ('Aion', 'CAR_BRAND'),
       ('Alfa Romeo', 'CAR_BRAND'),
       ('Anadol', 'CAR_BRAND'),
       ('Aston Martin', 'CAR_BRAND'),
       ('Audi', 'CAR_BRAND'),
       ('Bentley', 'CAR_BRAND'),
       ('BMW', 'CAR_BRAND'),
       ('Bugatti', 'CAR_BRAND'),
       ('Buick', 'CAR_BRAND'),
       ('BYD', 'CAR_BRAND'),
       ('Cadillac', 'CAR_BRAND'),
       ('Caterham', 'CAR_BRAND'),
       ('Chery', 'CAR_BRAND'),
       ('Chevrolet', 'CAR_BRAND'),
       ('Chrysler', 'CAR_BRAND'),
       ('Citroën', 'CAR_BRAND'),
       ('Dacia', 'CAR_BRAND'),
       ('Daewoo', 'CAR_BRAND'),
       ('Daihatsu', 'CAR_BRAND'),
       ('Dodge', 'CAR_BRAND'),
       ('DS Automobiles', 'CAR_BRAND'),
       ('Ferrari', 'CAR_BRAND'),
       ('Fiat', 'CAR_BRAND'),
       ('Fisker', 'CAR_BRAND'),
       ('Ford', 'CAR_BRAND'),
       ('Geely', 'CAR_BRAND'),
       ('Honda', 'CAR_BRAND'),
       ('Hyundai', 'CAR_BRAND'),
       ('Ikco', 'CAR_BRAND'),
       ('Infiniti', 'CAR_BRAND'),
       ('Isuzu', 'CAR_BRAND'),
       ('Jaguar', 'CAR_BRAND'),
       ('Kia', 'CAR_BRAND'),
       ('Lada', 'CAR_BRAND'),
       ('Lamborghini', 'CAR_BRAND'),
       ('Lancia', 'CAR_BRAND'),
       ('Lexus', 'CAR_BRAND'),
       ('Lincoln', 'CAR_BRAND'),
       ('Lotus', 'CAR_BRAND'),
       ('Marcos', 'CAR_BRAND'),
       ('Maserati', 'CAR_BRAND'),
       ('Mazda', 'CAR_BRAND'),
       ('McLaren', 'CAR_BRAND'),
       ('Mercedes - Benz', 'CAR_BRAND'),
       ('Mercury', 'CAR_BRAND'),
       ('MG', 'CAR_BRAND'),
       ('Mini', 'CAR_BRAND'),
       ('Mitsubishi', 'CAR_BRAND'),
       ('Moskwitsch', 'CAR_BRAND'),
       ('Nissan', 'CAR_BRAND'),
       ('Opel', 'CAR_BRAND'),
       ('Peugeot', 'CAR_BRAND'),
       ('Plymouth', 'CAR_BRAND'),
       ('Pontiac', 'CAR_BRAND'),
       ('Porsche', 'CAR_BRAND'),
       ('Proton', 'CAR_BRAND'),
       ('Renault', 'CAR_BRAND'),
       ('Rolls-Royce', 'CAR_BRAND'),
       ('Rover', 'CAR_BRAND'),
       ('Saab', 'CAR_BRAND'),
       ('Seat', 'CAR_BRAND'),
       ('Skoda', 'CAR_BRAND'),
       ('Smart', 'CAR_BRAND'),
       ('Subaru', 'CAR_BRAND'),
       ('Suzuki', 'CAR_BRAND'),
       ('Tata', 'CAR_BRAND'),
       ('Tesla', 'CAR_BRAND'),
       ('Tofaş', 'CAR_BRAND'),
       ('Toyota', 'CAR_BRAND'),
       ('Volkswagen', 'CAR_BRAND'),
       ('Volvo', 'CAR_BRAND');