CREATE TABLE brands
(
    id           bigserial not null
        constraint brands_pk
            primary key,
    name         text      not null,
    location     text      not null,
    feature_type text      not null
);

create index car_brands_asc_index on brands (name asc);

INSERT INTO brands(name, feature_type, location)
VALUES ('Acura', 'CAR_BRAND', 'car.brand.'),
       ('Aion', 'CAR_BRAND', 'car.brand.'),
       ('Alfa Romeo', 'CAR_BRAND', 'car.brand.'),
       ('Anadol', 'CAR_BRAND', 'car.brand.'),
       ('Aston Martin', 'CAR_BRAND', 'car.brand.'),
       ('Audi', 'CAR_BRAND', 'car.brand.'),
       ('Bentley', 'CAR_BRAND', 'car.brand.'),
       ('BMW', 'CAR_BRAND', 'car.brand.'),
       ('Bugatti', 'CAR_BRAND', 'car.brand.'),
       ('Buick', 'CAR_BRAND', 'car.brand.'),
       ('BYD', 'CAR_BRAND', 'car.brand.'),
       ('Cadillac', 'CAR_BRAND', 'car.brand.'),
       ('Caterham', 'CAR_BRAND', 'car.brand.'),
       ('Chery', 'CAR_BRAND', 'car.brand.'),
       ('Chevrolet', 'CAR_BRAND', 'car.brand.'),
       ('Chrysler', 'CAR_BRAND', 'car.brand.'),
       ('Citroën', 'CAR_BRAND', 'car.brand.'),
       ('Dacia', 'CAR_BRAND', 'car.brand.'),
       ('Daewoo', 'CAR_BRAND', 'car.brand.'),
       ('Daihatsu', 'CAR_BRAND', 'car.brand.'),
       ('Dodge', 'CAR_BRAND', 'car.brand.'),
       ('DS Automobiles', 'CAR_BRAND', 'car.brand.'),
       ('Ferrari', 'CAR_BRAND', 'car.brand.'),
       ('Fiat', 'CAR_BRAND', 'car.brand.'),
       ('Fisker', 'CAR_BRAND', 'car.brand.'),
       ('Ford', 'CAR_BRAND', 'car.brand.'),
       ('Geely', 'CAR_BRAND', 'car.brand.'),
       ('Honda', 'CAR_BRAND', 'car.brand.'),
       ('Hyundai', 'CAR_BRAND', 'car.brand.'),
       ('Ikco', 'CAR_BRAND', 'car.brand.'),
       ('Infiniti', 'CAR_BRAND', 'car.brand.'),
       ('Isuzu', 'CAR_BRAND', 'car.brand.'),
       ('Jaguar', 'CAR_BRAND', 'car.brand.'),
       ('Kia', 'CAR_BRAND', 'car.brand.'),
       ('Lada', 'CAR_BRAND', 'car.brand.'),
       ('Lamborghini', 'CAR_BRAND', 'car.brand.'),
       ('Lancia', 'CAR_BRAND', 'car.brand.'),
       ('Lexus', 'CAR_BRAND', 'car.brand.'),
       ('Lincoln', 'CAR_BRAND', 'car.brand.'),
       ('Lotus', 'CAR_BRAND', 'car.brand.'),
       ('Marcos', 'CAR_BRAND', 'car.brand.'),
       ('Maserati', 'CAR_BRAND', 'car.brand.'),
       ('Mazda', 'CAR_BRAND', 'car.brand.'),
       ('McLaren', 'CAR_BRAND', 'car.brand.'),
       ('Mercedes - Benz', 'CAR_BRAND', 'car.brand.'),
       ('Mercury', 'CAR_BRAND', 'car.brand.'),
       ('MG', 'CAR_BRAND', 'car.brand.'),
       ('Mini', 'CAR_BRAND', 'car.brand.'),
       ('Mitsubishi', 'CAR_BRAND', 'car.brand.'),
       ('Moskwitsch', 'CAR_BRAND', 'car.brand.'),
       ('Nissan', 'CAR_BRAND', 'car.brand.'),
       ('Opel', 'CAR_BRAND', 'car.brand.'),
       ('Peugeot', 'CAR_BRAND', 'car.brand.'),
       ('Plymouth', 'CAR_BRAND', 'car.brand.'),
       ('Pontiac', 'CAR_BRAND', 'car.brand.'),
       ('Porsche', 'CAR_BRAND', 'car.brand.'),
       ('Proton', 'CAR_BRAND', 'car.brand.'),
       ('Renault', 'CAR_BRAND', 'car.brand.'),
       ('Rolls-Royce', 'CAR_BRAND', 'car.brand.'),
       ('Rover', 'CAR_BRAND', 'car.brand.'),
       ('Saab', 'CAR_BRAND', 'car.brand.'),
       ('Seat', 'CAR_BRAND', 'car.brand.'),
       ('Skoda', 'CAR_BRAND', 'car.brand.'),
       ('Smart', 'CAR_BRAND', 'car.brand.'),
       ('Subaru', 'CAR_BRAND', 'car.brand.'),
       ('Suzuki', 'CAR_BRAND', 'car.brand.'),
       ('Tata', 'CAR_BRAND', 'car.brand.'),
       ('Tesla', 'CAR_BRAND', 'car.brand.'),
       ('Tofaş', 'CAR_BRAND', 'car.brand.'),
       ('Toyota', 'CAR_BRAND', 'car.brand.'),
       ('Volkswagen', 'CAR_BRAND', 'car.brand.'),
       ('Volvo', 'CAR_BRAND', 'car.brand.');