CREATE TABLE car_brands
(
    id   bigserial not null
        constraint car_brands_pk
            primary key,
    name text      not null
);

create index car_brands_asc_index on car_brands (name asc);

INSERT INTO car_brands(name)
VALUES ('Acura'),
       ('Aion'),
       ('Alfa Romeo'),
       ('Anadol'),
       ('Aston Martin'),
       ('Audi'),
       ('Bentley'),
       ('BMW'),
       ('Bugatti'),
       ('Buick'),
       ('BYD'),
       ('Cadillac'),
       ('Caterham'),
       ('Chery'),
       ('Chevrolet'),
       ('Chrysler'),
       ('Citroën'),
       ('Dacia'),
       ('Daewoo'),
       ('Daihatsu'),
       ('Dodge'),
       ('DS Automobiles'),
       ('Ferrari'),
       ('Fiat'),
       ('Fisker'),
       ('Ford'),
       ('Geely'),
       ('Honda'),
       ('Hyundai'),
       ('Ikco'),
       ('Infiniti'),
       ('Isuzu'),
       ('Jaguar'),
       ('Kia'),
       ('Lada'),
       ('Lamborghini'),
       ('Lancia'),
       ('Lexus'),
       ('Lincoln'),
       ('Lotus'),
       ('Marcos'),
       ('Maserati'),
       ('Mazda'),
       ('McLaren'),
       ('Mercedes - Benz'),
       ('Mercury'),
       ('MG'),
       ('Mini'),
       ('Mitsubishi'),
       ('Moskwitsch'),
       ('Nissan'),
       ('Opel'),
       ('Peugeot'),
       ('Plymouth'),
       ('Pontiac'),
       ('Porsche'),
       ('Proton'),
       ('Renault'),
       ('Rolls-Royce'),
       ('Rover'),
       ('Saab'),
       ('Seat'),
       ('Skoda'),
       ('Smart'),
       ('Subaru'),
       ('Suzuki'),
       ('Tata'),
       ('Tesla'),
       ('Tofaş'),
       ('Toyota'),
       ('Volkswagen'),
       ('Volvo');